### PR TITLE
Release: 3.4.0

### PR DESCRIPTION
**Pull request by tomusborne**

### CODE REVIEW

**Comment by DAnn2012** [comment]
Hello @tomusborne 

Please also add this PR of mine #570  to the next version 3.4.0.

Thank you.

**Comment by SchneiderSam** [comment]
@tomusborne  Thanks for working on GB. 

There hasn't been much happening here for a while, which made me think: oh, what's going on here? Must be quite challenging with a small team in the WP world, right? Regardless, I think it's really sensible that you're pushing GB more and waiting to see how the block theme world evolves. Is Jean Paiva no longer working for you?

**Comment by tomusborne** [comment]
Jean is no longer on the team, but we hired two new devs this week which will be super helpful.

We're working through a few more important issues here for GP, then we'll be releasing the alpha versions.

Thanks!

**Comment by SchneiderSam** [comment]
@tomusborne Okay, being a programmer and CEO at the same time can be quite exhausting. Kudos to you for managing it all and staying so focused. Very inspiring!

**Pull request merged**
