### PR TITLE
improve homepage SEO

### PR DESCRIPTION
**Pull request by luizbills**
As suggested by underscores
https://github.com/Automattic/_s/blob/master/header.php#L29-L34

### CODE REVIEW

**Comment by tomusborne** [comment]
Looks like a good change!

Can we confirm that having the site title as an H1 doesn't conflict with any of the options? (Typography, Colors etc..)

**Comment by bhambrabland** [comment]
Agreed, good change.

--

Regards

Richard Bland

----
Sent from my mobile
----

BhambraBland

Websites with Passion, Expertise, and WordPress at the core.

www.bhambrabland.co.uk

07933110282

**Comment by luizbills** [comment]
I did not have time today, Tom. But on saturday or sunday I will check for possibles conflicts.

**Comment by tomusborne** [comment]
I just played around with it and I don't think there are any conflicts.

That doesn't include people who have added custom CSS specific to the `p` element, but it should be good to go for the next version :)

**Comment by luizbills** [comment]
nice :+1:

**Pull request merged**
