### PR TITLE
Add global color defaults

### PR DESCRIPTION
**Pull request by tomusborne**
Adds default global colors and applies them as our default colors.

Needs testing to ensure that defaults on existing sites aren't overwritten.

Should we prefix the global color variable names with `gp-` to prevent conflicts?

### CODE REVIEW

**Comment by JeanPaiva** [comment]
@tomusborne I did some research about color in design systems naming conventions and does not exist anything very solid.
A good practice is to use the color name + lightness number. Example: `primary-blue` & `primary-blue-50`.

But for the general colors it does not apply very smoothly. If the user changes the color it lost all it's meaning.

If we thing in the global palette as a theme, where in the future we can enable users to have multiple themes, to display the website base on custom rules, the naming background, text is makes way more sense.

My suggestion would be to go similar to this:

- background
- background-light
- background-dark
- text-light
- text-dark
- accent-light
- accent-dark

**Comment by JeanPaiva** [comment]
How we are on this? Saw that some messages that I added were removed, you also did some changes that are not in the final PR anymore.

For the naming convention the current one works for me. If we think that this should be changed in the future we can do it for new users.

**Comment by tomusborne** [comment]
>  Saw that some messages that I added were removed

It should still be there or was there another one?: https://github.com/tomusborne/generatepress/pull/165/files#diff-3855d7a5a82cfae12f9d782656a8d2250d2a7f5c88498a0b14bcd413756e851cR153

> you also did some changes that are not in the final PR anymore

Anything specific? Haven't done much to this PR in the last few days. It should only:

1. Add the defaults
2. Change core theme defaults to the `var()` values
3. Add old theme defaults to the migrator

I think this naming convention works as well.

**Comment by JeanPaiva** [comment]
You did this: https://github.com/tomusborne/generatepress/pull/165/commits/27bc671f0208bba63413a904ae9b6ea8a6637ced

Let's remove the messages update from this PR and merge only the color defaults. I can create another PR for the messages alone. What do you think?

**Comment by tomusborne** [comment]
Ah, my bad. Yea, let's do that.

**Pull request merged**
