### PR TITLE
Allow dynamic typography CSS to split

### PR DESCRIPTION
**Pull request by tomusborne**
This allows us to split up the CSS generated by dynamic typography.

For example, the Secondary Nav styles need to show up after the Secondary Nav stylesheet, so we can do this:

```
if ( class_exists( 'GeneratePress_Typography' ) ) {
    wp_add_inline_style( 'generate-secondary-nav', GeneratePress_Typography::get_css( 'secondary-nav' ) );
}

add_filter( 'generate_typography_element_exclusions', 'generate_secondary_nav_typography_exclusions' );
/**
 * Exclude our selectors from the main CSS generation.
 *
 * @param array $exclusions The current exclusions.
 */
function generate_secondary_nav_typography_exclusions( $exclusions ) {
	$exclusions = 'secondary-nav';

	return $exclusions;
}
```

There might be a better way to do this, this is just what I could come up with so far.

The ability to do this will be super useful when adding typography for WooCommerce as well.

### CODE REVIEW

**Review by JeanPaiva — APPROVED** [review]
I will test in the GPP PR.

**Comment by tomusborne** [comment]
@JeanPaiva Not sure if there's a simpler way to do this. This isn't too bad, just requires the exclusions filter and the start of the names to all start the same if we want to compile the CSS separately.

**Comment by JeanPaiva** [comment]
@tomusborne I think a cleaner solution would be to change the filter to have the selectors to remove `generate_typography_selector_exclusions` that way we can do something like this:

```php
$typography = array_filter( (array) $typography, function($data) use ($exclusions) {
    return ! in_array($data['selector'], $exclusions);
});
```

**Comment by tomusborne** [comment]
@JeanPaiva So much better. My only worry is older versions of PHP fatal erroring because of the anonymous function. We do set a minimum PHP version in the theme, but I'm paranoid.. Maybe time to get over it? haha

**Comment by JeanPaiva** [comment]
I think anonymous functions were introduced in 5.3.0. But users should be forced to upgrade at least to 7.1 at some point. The perf boost is huge.

**Comment by tomusborne** [comment]
I agree. Now how does this handle Secondary Nav (in this case) adding its own CSS? Before, we would specify the `$module` in the args.

**Comment by JeanPaiva** [comment]
I forgot about that...haha I'm trying something here

**Review by JeanPaiva — APPROVED** [review]

**Review by JeanPaiva — APPROVED** [review]

**Pull request merged**
