### PR TITLE
Show the current value in the advanced select

### PR DESCRIPTION
**Pull request by tomusborne**
The Advanced Select component is currently missing the current saved value. This should fix that.

@JeanPaiva There might be a way easier way to do this? It should work for grouped selects and non-grouped selects.

### CODE REVIEW

**Review by JeanPaiva — COMMENTED** [review]
For this component to be extremely reusable we can go like this:

```import './style.scss';
import Select from 'react-select';

const GeneratePressAdvancedSelect = ( componentProps ) => {
	const customStyles = {
		indicatorSeparator: () => ( {
			display: 'none',
		} ),

		indicatorsContainer: ( provided ) => ( {
			...provided,
			maxHeight: '30px',
		} ),
	};

	const customTheme = ( provided ) => ( {
		borderRadius: 2,
		colors: {
			...provided.colors,
			primary: 'var(--wp-admin-theme-color)',
			neutral20: '#757575',
			neutral30: '#757575',
		},
		spacing: {
			controlHeight: 30,
			baseUnit: 3,
			menuGutter: 3,
		},
	} );

	const defaultProps = {
		className: 'generate-advanced-select',
		classNamePrefix: 'generate-advanced-select',
		isSearchable: true,
		styles: customStyles,
		instanceId: 'input-field',
		maxMenuHeight: 130,
		theme: customTheme
	};

	const props = Object.assign({}, defaultProps, componentProps);

	return ( <Select {...props} /> );
};

export default GeneratePressAdvancedSelect;
```

We can use all React-Select props and override the ones we set. By doing this would require to change the function `GeneratePressFontManagerControlForm:onFontShortcut` to receive the object instead of the value. This way if you save the value returned from the `onChange` in your component you just need to re-pass him as value to the select.

```
<AdvancedSelect onChange={myOnChange} value={valueReturnedFromMyOnChange} ...otherProps />

**Comment by tomusborne** [comment]
That definitely sounds better. I assume we'd still be able to opt-out of the value if needed (https://github.com/tomusborne/generatepress/pull/183)?

**Comment by JeanPaiva** [comment]
Yes, the `current` prop will not work anymore, you can remove entirely.

**Comment by tomusborne** [comment]
This shouldn't be necessary anymore: https://github.com/tomusborne/generatepress/pull/183

**Comment by tomusborne** [comment]
We'll work this into https://github.com/tomusborne/generatepress/pull/181 once we merge https://github.com/tomusborne/generatepress/pull/184

**Pull request closed without merging**
