### PR TITLE
Fix Support Links in various files

### LINKED ISSUE #575: Update the Support link in theme dashboar
The Support link in the theme dashboard needs to be updated:
https://www.screencast.com/t/SaZIYrqp

### PR DESCRIPTION
**Pull request by masteradhoc**
Fixes #575
PR updates the Support link in theme dashboard

### CODE REVIEW

**Comment by tomusborne** [comment]
Thanks for this @masteradhoc!

I added a comment here for discussion: https://github.com/tomusborne/generatepress/issues/575#issuecomment-1777743406

**Comment by masteradhoc** [comment]
@tomusborne no just tell me what you think would be better. No issue to change this 👍🏻

**Comment by tomusborne** [comment]
@masteradhoc Just noticed that as well, definitely not the right link.

So we either want to direct people to [generate.support](https://generate.support) or the [GP contact page](https://generatepress.com/contact).

Going to think on this a little. We may direct `https://generatepress.com/support` to `https://generatepress.com/contact` as the old archives shouldn't be at `/support` anymore.

Will update PR once we choose a direction.

**Comment by tomusborne** [comment]
We decided to continue to use `https://generatepress.com/support`, but update the page with the latest info.

Appreciate the PR and the nudge to get this done - thank you!

**Pull request closed without merging**
