### PR TITLE
Add full settings key to color group to allow override

### PR DESCRIPTION
**Pull request by JeanPaiva**
This is to allow GPP to override the settings namespace. Related to https://github.com/tomusborne/gp-premium/pull/198

### CODE REVIEW

**Comment by tomusborne** [comment]
Reviewed and tested, good to go!

**Review by tomusborne — APPROVED** [review]
Reviewed and tested, looks good!

**Comment by JeanPaiva** [comment]
@tomusborne Added the fix for li:not().sfHover

**Comment by tomusborne** [comment]
@JeanPaiva looks like it's there twice now: `.main-nav ul ul li.sfHover:not([class*="current-menu-"]).sfHover`

**Comment by JeanPaiva** [comment]
Fixed :)

**Comment by tomusborne** [comment]
Looks good!

**Pull request merged**
