### PR TITLE
Typography element advanced select

### PR DESCRIPTION
**Pull request by tomusborne**
This turns the typography element select into the Advanced Select component.

It also adds the necessary filters to filter the items.

### CODE REVIEW

**Comment by tomusborne** [comment]
The Advanced Select needs the saved value now that it's not only for the font family shortcut.

**Comment by tomusborne** [comment]
Showing the saved value is in this PR: https://github.com/tomusborne/generatepress/pull/182

**Comment by tomusborne** [comment]
This will need to be updated once we merge https://github.com/tomusborne/generatepress/pull/183.

**Comment by tomusborne** [comment]
Not sure what the best way to get the current value here is. There also seems to be some height issues when adding a new Typography Element. Like the dropdown isn't overflowing the popover.

**Comment by tomusborne** [comment]
@JeanPaiva this is ready for review whenever you can. It's blocking some GPP stuff I'm working on.

**Review by JeanPaiva — APPROVED** [review]
Looks good

**Pull request merged**
