### PR TITLE
Propose: filter "generate_navigation_search_icon"

### PR DESCRIPTION
**Pull request by luizbills**
To make possible change the search icon of the main menu.

### CODE REVIEW

**Comment by generatepress** [comment]
Thank you!

This will also need to be updated in template-tags.php in the generate_menu_search_icon() function and the generate_mobile_menu_search_icon() function.

Would you like to add those changes to the pull request?

Let me know :)

**Comment by luizbills** [comment]
Can you test later, please?

**Comment by generatepress** [comment]
Absolutely!

Thanks a lot :)

**Comment by luizbills** [comment]
you're welcome :D

**Comment by tomusborne** [comment]
One issue I've found here is how the JS switches the icon from the search icon to close icon:
https://github.com/tomusborne/generatepress/blob/1.3.40/js/navigation-search.js#L12
https://github.com/tomusborne/generatepress/blob/1.3.40/js/navigation-search.js#L19
https://github.com/tomusborne/generatepress/blob/1.3.40/js/navigation-search.js#L33

I'll need to think about how to make that filterable as well based on the above pull request.

**Comment by luizbills** [comment]
maybe a `span.icon-wrapper` container: `$('.search-item .icon-wrapper').replaceWith(...)`

**Comment by tomusborne** [comment]
But if a user changes what the icon is, how does the javascript know what to replace it with/restore it as?

**Comment by luizbills** [comment]
something like this:
```js
// when user opens the search
$wrapper = $('.search-item .icon-wrapper');
if ( search_closed ) {
    if ( !generate_search_icon ) generate_search_icon = $wrapper.html();
    $wrapper.html( close_icon );
}
```

```js
// when user closes the search
if ( !search_closed ) {
    $wrapper.html( generate_search_icon );
}
```

**Pull request closed without merging**
