### PR TITLE
Fix the alignment of the with unit component

### PR DESCRIPTION
**Pull request by tomusborne**
This was a weird one to unpick and figure out.

Without it, we were seeing this misalignment: https://www.screencast.com/t/YpMQ7e0F1

With this PR, it looks like this: https://www.screencast.com/t/4XtnDG0a

Not perfect, but a definite improvement.

### CODE REVIEW

**Comment by JeanPaiva** [comment]
@tomusborne what about something like this:

```css
.components-generate-range-control-input input {
  max-height: 30px;
}
```
alignment

**Comment by tomusborne** [comment]
@JeanPaiva that looks way better.

**Comment by tomusborne** [comment]
That didn't do it for me in dev tools? This did though:

```
.components-generate-range-control--range {
    max-height: 30px;
}
```

**Comment by tomusborne** [comment]
Combination of both seems to be perfect: https://www.screencast.com/t/gIlj2AG6kA

**Pull request merged**
