### PR TITLE
Restructure functions and files

### PR DESCRIPTION
**Pull request by tomusborne**
`generate_get_min_suffix()`

Deprecated - only used once in the theme, so no need for its own function.

**Potential conflict (PC):** Low

---

`generate_get_layout()` -> `generate_get_sidebar_layout()`

Renamed to be more specific. Old function deprecated to avoid any errors.

**PC:** Low - deprecated function exists as fallback.

---

`generate_get_footer_widgets()` -> `generate_get_footer_widget_count()`

Renamed to be more specific. Old function deprecated to avoid any errors.

**PC:** Low - deprecated function exists as fallback.

---

`generate_get_setting()` -> `generate_get_option()`

Renamed to fit with WP function get_option()

**PC:** Low - deprecated function exists as fallback.

---

`generate_padding_css()` -> `generate_get_shorthand_spacing()`

Renamed to be more specific.

**PC:** Low - deprecated function exists as fallback.

---

`generate_right_sidebar_class` -> `generate_do_attr( 'right-sidebar' )`
`generate_get_right_sidebar_class` -> `generate_get_attr( 'right-sidebar' )`
`generate_left_sidebar_class` -> `generate_do_attr( 'left-sidebar' )`
`generate_get_left_sidebar_class` -> `generate_get_attr( 'left-sidebar' )`
`generate_content_class` -> `generate_do_attr( 'primary' )`
`generate_get_content_class` -> `generate_get_attr( 'primary' )`
`generate_header_class` -> `generate_do_attr( 'header' )`
`generate_get_header_class` -> `generate_get_attr( 'header' )`
`generate_inside_header_class` -> `generate_do_attr( 'inside-header' )`
`generate_get_inside_header_class` -> `generate_get_attr( 'inside-header' )`
`generate_container_class` -> `generate_do_attr( 'page' )`
`generate_get_container_class` -> `generate_get_attr( 'page' )`
`generate_navigation_class` -> `generate_do_attr( 'navigation' )`
`generate_get_navigation_class` -> `generate_get_attr( 'navigation' )`
`generate_inside_navigation_class` -> `generate_do_attr( 'inside-navigation' )`
`generate_menu_class` -> `generate_do_attr( 'menu' )`
`generate_get_menu_class` -> `generate_do_attr( 'menu' )`
`generate_main_class` -> `generate_do_attr( 'main' )`
`generate_get_main_class` -> `generate_do_attr( 'main' )`
`generate_footer_class` -> `generate_do_attr( 'footer' )`
`generate_get_footer_class` -> `generate_do_attr( 'footer' )`
`generate_inside_footer_class` -> `generate_do_attr( 'inside-footer' )`
`generate_top_bar_class` -> `generate_do_attr( 'top-bar' )`

All class functions replaced by `generate_do_attr()` and `generate_get_attr()` which handle all element attributes.

**PC:** Medium - child themes will have these functions, but they've been deprecated to avoid any errors. Developers should update their child themes as needed.

---

`generate_body_schema()` -> `generate_do_attr( 'body' )`
`generate_article_schema()` -> `generate_do_attr( 'post' )`

Schema and other element attributes are now handled by `generate_do_attr()`.

**PC:** Medium - child themes will have these functions, but they've been deprecated to avoid any errors. Developers should update their child themes as needed.

---

`generate_show_title()` -> `generate_show_content_title()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

`generate_show_excerpt()` -> `generate_show_post_excerpt()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

`generate_get_link_url()` -> `generate_get_url_in_content()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

`generate_categorized_blog()`

Deprecated. No longer needed.

**PC:** Low - deprecated to avoid any errors.

---

`generate_category_transient_flusher()`

Deprecated. No longer needed.

**PC:** Low - deprecated to avoid any errors.

---

`generate_remove_caption_padding()` -> `generate_set_caption_width()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

`generate_get_navigation_location()` -> `generate_get_primary_menu_location()`

More specific, and allows us to remove function_exists() without chance of triggering a fatal error.

**PC:** Low - deprecated to avoid any errors.

---

`generate_get_premium_url()` -> `generate_get_upsell_url()`

More specific.

**PC:** Low - deprecated to avoid any errors.

---

**The rest of these are internal functions, but have been deprecated anyways to avoid any warnings or notices. If you're hooking/unhooking any of these functions, make sure to adjust your code.**

---

`generate_setup()` -> `generate_setup_theme()`

Renamed to be more specific and avoid any name conflicts with other functions.

**PC:** Very low

---

`generate_scripts()` -> `generate_enqueue_scripts()`

Renamed to be more specific and avoid any name conflicts with other functions.

**PC:** Very low

---

`generate_create_menu()` -> `generate_do_dashboard_menu()`

Renamed to be more specific.

**PC:** Very low

---

`generate_options_styles()` -> `generate_enqueue_dashboard_scripts()`

Renamed to be more specific.

**PC:** Very low

---

`generate_settings_page()` -> `generate_do_dashboard_page()`

Renamed to be more specific.

**PC:** Very low

---

`generate_reset_customizer_settings()` -> `generate_do_customizer_reset()`

Renamed to fit with naming structure of other functions.

**PC:** Very low

---

`generate_admin_errors` -> `generate_do_admin_errors()`

Renamed to avoid function naming conflicts with other third-party functions.

**PC:** Very low

---

Functions that were used to add classes to elements have been deprecated, and the classes have been filtered into the element attributes.

`generate_body_classes()` -> `generate_set_body_attributes()`
`generate_top_bar_classes()` -> `generate_set_top_bar_attributes()`
`generate_right_sidebar_classes()` -> `generate_set_right_sidebar_attributes()`
`generate_left_sidebar_classes()` -> `generate_set_left_sidebar_attributes()`
`generate_content_classes()` -> `generate_set_primary_attributes()`
`generate_header_classes()` -> `generate_set_header_attributes()`
`generate_inside_header_classes()` -> `generate_set_inside_header_attributes()`
`generate_navigation_classes()` -> `generate_set_navigation_attributes()`
`generate_inside_navigation_classes()` -> `generate_set_inside_navigation_attributes()`
`generate_menu_classes()` -> `generate_set_menu_attributes()`
`generate_footer_classes()` -> `generate_set_footer_attributes()`
`generate_inside_footer_classes()` -> `generate_set_inside_footer_attributes()`
`generate_main_classes()` -> `generate_set_main_attributes()`
`generate_post_classes()` -> `generate_set_post_attributes()`

**PC:** Very low - these are internal functions. If you're filtering in your own classes using different function names, you're good to go.

---

`generate_widgets_init()` -> `generate_register_widget_areas()`

Rename to be more specific.

**PC:** Very low

---

These functions have been deprecated and replaced by the new Layout meta box.

`generate_add_layout_meta_box()`
`generate_show_layout_meta_box()`
`generate_save_layout_meta()`
`generate_add_footer_widget_meta_box()`
`generate_show_footer_widget_meta_box()`
`generate_save_footer_widget_meta()`
`generate_add_page_builder_meta_box()`
`generate_show_page_builder_meta_box()`
`generate_save_page_builder_meta()`
`generate_add_de_meta_box()`
`generate_show_de_meta_box()`
`generate_save_de_meta()`

If you're unhooking or hiding the meta boxes, you will have to update your code. The meta box ID of the new Layout meta box is: `generate_layout_options_meta_box`

All of the above functions have been replaced by these functions:

`generate_register_layout_meta_box()`
`generate_do_layout_meta_box()`
`generate_save_layout_meta_data()`

**PC:** Low - if you're removing any of the existing meta boxes, you'll need to use the new layout meta box ID.

---

`generate_additional_spacing()`

Deprecated. No longer needed.

**PC:** Very low

---

`generate_mobile_search_spacing_fallback_css()`

Deprecated. No longer needed.

**PC:** Very low

---

`generate_smart_content()` -> `generate_set_content_width()`

Rename to something more specific.

**PC:** Very low

---

`generate_enhanced_image_navigation()`

Deprecated. No longer needed.

**PC:** Very low

---

`generate_page_menu_args()` -> `generate_set_home_link_fallback()`

Rename to something more specific.

**PC:** Very low

---

`generate_disable_title()` -> `generate_remove_content_title()`

Renamed to something more specific.

**PC:** Very low

---

`generate_resource_hints()` -> `generate_set_google_font_resource_hints()`

Renamed to something more specific.

**PC:** Very low

### CODE REVIEW

**Comment by luizbills** [comment]
consider releasing as 2.0 or 1.4, because maybe it can break some customized child themes

**Comment by tomusborne** [comment]
Considering a 2.0 release, however nothing should break. All removed functions have been deprecated and will return the desired functionality along with a deprecated notice allowing developers to switch their functions.

**Comment by tomusborne** [comment]
Thinking about this more, I think 2.0 might be a good idea for this release. While it won't break existing child themes, developers will need to update some functions with the new ones etc..

**Comment by luizbills** [comment]
It might be a good idea to also show a warning in admin, after updating to `2.0`.

**Comment by tomusborne** [comment]
What would it warn people of?

**Comment by luizbills** [comment]
A warning just for developers about possible conflicts because of renamed functions. Pointing to a changelog or developer-specific guide would also be good.

**Comment by tomusborne** [comment]
Might be a good idea, but admin notices are typically not allowed on WP.org. I'll ask for clarification.

Here's a list of deprecated functions and their replacements. I'll update this post as things change.

`generate_get_min_suffix()`

Deprecated - only used once in the theme, so no need for its own function.

**Potential conflict (PC):** Low

---

`generate_get_layout()` -> `generate_get_sidebar_layout()`

Renamed to be more specific. Old function deprecated to avoid any errors.

**PC:** Low - deprecated function exists as fallback.

---

`generate_get_footer_widgets()` -> `generate_get_footer_widget_count()`

Renamed to be more specific. Old function deprecated to avoid any errors.

**PC:** Low - deprecated function exists as fallback.

---

`generate_get_setting()` -> `generate_get_option()`

Renamed to fit with WP function get_option()

**PC:** Low - deprecated function exists as fallback.

---

`generate_padding_css()` -> `generate_shorthand_spacing_css()`

Renamed to be more specific.

**PC:** Low - deprecated function exists as fallback.

---

`generate_right_sidebar_class` -> `generate_do_attr( 'right-sidebar' )`
`generate_get_right_sidebar_class` -> `generate_get_attr( 'right-sidebar' )`
`generate_left_sidebar_class` -> `generate_do_attr( 'left-sidebar' )`
`generate_get_left_sidebar_class` -> `generate_get_attr( 'left-sidebar' )`
`generate_content_class` -> `generate_do_attr( 'primary' )`
`generate_get_content_class` -> `generate_get_attr( 'primary' )`
`generate_header_class` -> `generate_do_attr( 'header' )`
`generate_get_header_class` -> `generate_get_attr( 'header' )`
`generate_inside_header_class` -> `generate_do_attr( 'inside-header' )`
`generate_get_inside_header_class` -> `generate_get_attr( 'inside-header' )`
`generate_container_class` -> `generate_do_attr( 'page' )`
`generate_get_container_class` -> `generate_get_attr( 'page' )`
`generate_navigation_class` -> `generate_do_attr( 'navigation' )`
`generate_get_navigation_class` -> `generate_get_attr( 'navigation' )`
`generate_inside_navigation_class` -> `generate_do_attr( 'inside-navigation' )`
`generate_menu_class` -> `generate_do_attr( 'menu' )`
`generate_get_menu_class` -> `generate_do_attr( 'menu' )`
`generate_main_class` -> `generate_do_attr( 'main' )`
`generate_get_main_class` -> `generate_do_attr( 'main' )`
`generate_footer_class` -> `generate_do_attr( 'footer' )`
`generate_get_footer_class` -> `generate_do_attr( 'footer' )`
`generate_inside_footer_class` -> `generate_do_attr( 'inside-footer' )`
`generate_top_bar_class` -> `generate_do_attr( 'top-bar' )`

All class functions replaced by `generate_do_attr()` and `generate_get_attr()` which handle all element attributes.

**PC:** Medium - child themes will have these functions, but they've been deprecated to avoid any errors. Developers should update their child themes as needed.

---

`generate_body_schema()` -> `generate_do_attr( 'body' )`
`generate_article_schema()` -> `generate_do_attr( 'post' )`

Schema and other element attributes are now handled by `generate_do_attr()`.

**PC:** Medium - child themes will have these functions, but they've been deprecated to avoid any errors. Developers should update their child themes as needed.

---

`generate_show_title()` -> `generate_show_content_title()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

`generate_show_excerpt()` -> `generate_show_post_excerpt()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

`generate_get_link_url()` -> `generate_get_first_content_url()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

`generate_categorized_blog()` -> deprecated

No longer needed.

**PC:** Low - deprecated to avoid any errors.

---

`generate_category_transient_flusher()` -> deprecated

No longer needed.

**PC:** Low - deprecated to avoid any errors.

---

`generate_remove_caption_padding()` -> `generate_adjust_caption_width()`

Renamed to be more specific.

**PC:** Low - deprecated to avoid any errors.

---

**The rest of these are internal functions, but have been deprecated anyways to avoid any warnings or notices. If you're hooking/unhooking any of these functions, make sure to adjust your code.**

---

`generate_setup()` -> `generate_setup_theme`

Renamed to be more specific and avoid any name conflicts with other functions.

**PC:** Very low

---

`generate_scripts()` -> `generate_enqueue_scripts()`

Renamed to be more specific and avoid any name conflicts with other functions.

**PC:** Very low

---

`generate_create_menu()` -> `generate_do_dashboard_menu()`

Renamed to be more specific.

**PC:** Very low

---

`generate_options_styles()` -> `generate_enqueue_dashboard_scripts()`

Renamed to be more specific.

**PC:** Very low

---

`generate_settings_page()` -> `generate_do_dashboard_page()`

Renamed to be more specific.

**PC:** Very low

---

`generate_reset_customizer_settings()` -> `generate_do_customizer_reset()`

Renamed to fit with naming structure of other functions.

**PC:** Very low

---

`generate_admin_errors` -> `generate_do_admin_errors()`

Renamed to avoid function naming conflicts with other third-party functions.

**PC:** Very low

---

Functions that were used to add classes to elements have been deprecated, and the classes have been filtered into the element attributes.

`generate_body_classes()` -> `generate_set_body_attributes()`
`generate_top_bar_classes()` -> `generate_set_top_bar_attributes()`
`generate_right_sidebar_classes()` -> `generate_set_right_sidebar_attributes()`
`generate_left_sidebar_classes()` -> `generate_set_left_sidebar_attributes()`
`generate_content_classes()` -> `generate_set_primary_attributes()`
`generate_header_classes()` -> `generate_set_header_attributes()`
`generate_inside_header_classes()` -> `generate_set_inside_header_attributes()`
`generate_navigation_classes()` -> `generate_set_navigation_attributes()`
`generate_inside_navigation_classes()` -> `generate_set_inside_navigation_attributes()`
`generate_menu_classes()` -> `generate_set_menu_attributes()`
`generate_footer_classes()` -> `generate_set_footer_attributes()`
`generate_inside_footer_classes()` -> `generate_set_inside_footer_attributes()`
`generate_main_classes()` -> `generate_set_main_attributes()`
`generate_post_classes()` -> `generate_set_post_attributes()`

**PC:** Very low - these are internal functions. If you're filtering in your own classes using different function names, you're good to go.

---

`generate_widgets_init()` -> `generate_register_widgets()`

Rename to be more specific.

**PC:** Very low

---

These functions have been deprecated and replaced by the new Layout meta box.

`generate_add_layout_meta_box()`
`generate_show_layout_meta_box()`
`generate_save_layout_meta()`
`generate_add_footer_widget_meta_box()`
`generate_show_footer_widget_meta_box()`
`generate_save_footer_widget_meta()`
`generate_add_page_builder_meta_box()`
`generate_show_page_builder_meta_box()`
`generate_save_page_builder_meta()`
`generate_add_de_meta_box()`
`generate_show_de_meta_box()`
`generate_save_de_meta()`

If you're unhooking or hiding the meta boxes, you will have to update your code. The meta box ID of the new Layout meta box is: `generate_layout_options_meta_box`

All of the above functions have been replaced by these functions:

`generate_register_layout_meta_box()`
`generate_do_layout_meta_box()`
`generate_save_layout_meta_data()`

**PC:** Low - if you're removing any of the existing meta boxes, you'll need to use the new layout meta box ID.

---

`generate_additional_spacing()` - deprecated

No longer needed.

**PC:** Very low

---

`generate_mobile_search_spacing_fallback_css()` - deprecated

**PC:** Very low

---

`generate_smart_content()` -> `generate_set_content_width()`

Rename to something more specific.

**PC:** Very low

---

`generate_enhanced_image_navigation()` - deprecated

No longer needed.

**PC:** Very low

---

`generate_page_menu_args()` - `generate_set_home_link_fallback()`

Rename to something more specific.

**PC:** Very low

---

`generate_disable_title()` - `generate_remove_content_title()`

Renamed to something more specific.

**PC:** Very low

---

`generate_resource_hints()` -> `generate_google_font_resource_hints()`

Renamed to something more specific.

**PC:** Very low

**Pull request closed without merging**
