### PR TITLE
More extendable breakpoints

### PR DESCRIPTION
**Pull request by luizbills**
Just a idea useful to: 

- change the breakpoint unit to `em`;
- use more than 1 limit: `(min-width: 30em) and (max-width: 60em)`
- or to specify other things: `screen and (max-width: 768px)`
- ect etc etc ...

P.S: Already tested.

### CODE REVIEW

**Comment by tomusborne** [comment]
Yup, I like this.

One issue, what if someone is already using the generate_mobile_breakpoint filter with a value like 600px? Doing this would break their media query.

I wonder if it's worth changing the filter name. That way, their filter just wouldn't work (wouldn't break anything), and they would have to come ask what it changed to.

**Comment by luizbills** [comment]
Good idea. Then, something like this:

```php
$mobile = apply_filters( 'generate_mobile_breakpoint', '768px' );
$mobile = apply_filters( 'generate_mobile_breakpoint_media', '(max-width:' . $mobile . ')' );
$output .= '@media ' . esc_attr( $mobile ) ...
```

What did you think?

**Comment by tomusborne** [comment]
Not too worried about generate_mobile_breakpoint. It was never documented and hasn't been utilised fully yet.

I've gone ahead and done this: https://github.com/tomusborne/generatepress/commit/9bd047d6af2ae2275a315681c3a1fabacc1909d2

Really appreciate your ideas!

**Comment by luizbills** [comment]
Thanks.
And I really appreciate your theme.

**Pull request closed without merging**
