### PR TITLE
Integrate dynamic attributes

### PR DESCRIPTION
**Pull request by tomusborne**
This PR adds the ability to filter in dynamic attributes to our theme elements using `generate_do_attr()` or `generate_get_attr()`.

Previously, we were using `generate_do_element_classes()` and `generate_get_element_classes()` so the classes were filterable.

We need to make sure all elements using these functions are still receiving their classes being added in `markup.php`. I checked each element as I went and didn't notice any issues.

This also handles adding necessary `aria-label` attributes to HTML5 elements that need them.

### CODE REVIEW

**Review by JeanPaiva — APPROVED** [review]
Thank you for the last return, I forget to add it on Friday. All good on my end, tried with some sites from the library, found nothing.

**Comment by tomusborne** [comment]
@JeanPaiva are there any noticeable performance changes between this branch and `3.1.0`?

**Comment by JeanPaiva** [comment]
I'll run some perf tests later. I let you know the results

**Comment by JeanPaiva** [comment]
@tomusborne here's the result of my tests:

Test environment:
- All plugins disabled
- Default GP settings
- Clean WP install

Results:

Branch `master` home page:
master-home-page
Branch `master` single page
master-single-page

Branch `release/3.1.0` home page:
3 1-home-page
Branch `release/3.1.0` single page:
3 1-single-page

Branch `dynamic-attributes` home page:
dynamic-home-page
Branch `dynamic-attributes` single page:
dynamic-single-page

**Comment by tomusborne** [comment]
Interesting, well at least we know this PR isn't causing any performance issues.

I wonder what happened between 3.1 and master to cause those differences. That's going to bug me.

**Comment by JeanPaiva** [comment]
Yes, it's weird. We need to improve the perf tools to find bottlenecks. The PR is good for me.

**Pull request merged**
